"""Add primary_soil_moisture, unit, and device_info_json to SensorData

Revision ID: 942f7358fc14
Revises: 
Create Date: 2025-05-20 19:28:17.257869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942f7358fc14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_soil_moisture_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('primary_soil_moisture_unit', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('device_info_json', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_column('device_info_json')
        batch_op.drop_column('primary_soil_moisture_unit')
        batch_op.drop_column('primary_soil_moisture_value')

    # ### end Alembic commands ###
